# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_auto_20190420_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
