# Generated by Django 2.0.13 on 2019-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0004_auto_20190420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('promotion', 'Promotion'), ('open_event', 'Open Event')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('buy_song_cover', 'Buy Song Cover'), ('register_song', 'Register Song'), ('register_model_photo', 'Register Model Photo')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('credit', 'Credit'), ('cash', 'Cash'), ('bank', 'Bank'), ('gift_card_culture', 'Gift Card(Culture)')], max_length=256, null=True),
        ),
    ]
