# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0005_auto_20190424_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('open_event', 'Open Event'), ('test', 'Test'), ('promotion', 'Promotion')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_song', 'Register Song'), ('register_model_photo', 'Register Model Photo'), ('buy_song_cover', 'Buy Song Cover')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('bank', 'Bank'), ('test', 'Test'), ('gift_card_culture', 'Gift Card(Culture)'), ('cash', 'Cash')], max_length=256, null=True),
        ),
    ]
