# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0006_auto_20190424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('test', 'Test'), ('open_event', 'Open Event')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_model_photo', 'Register Model Photo'), ('register_song', 'Register Song'), ('buy_song_cover', 'Buy Song Cover')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('gift_card_culture', 'Gift Card(Culture)'), ('credit', 'Credit'), ('bank', 'Bank'), ('test', 'Test'), ('cash', 'Cash')], max_length=256, null=True),
        ),
    ]
