# Generated by Django 2.0.13 on 2019-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0007_auto_20190424_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('open_event', 'Open Event'), ('promotion', 'Promotion'), ('test', 'Test')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_model_photo', 'Register Model Photo'), ('buy_song_cover', 'Buy Song Cover'), ('register_song', 'Register Song')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('bank', 'Bank'), ('credit', 'Credit'), ('gift_card_culture', 'Gift Card(Culture)'), ('cash', 'Cash')], max_length=256, null=True),
        ),
    ]
