# Generated by Django 2.0.13 on 2019-04-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0008_auto_20190424_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('test', 'Test'), ('open_event', 'Open Event')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_song', 'Register Song'), ('buy_song_cover', 'Buy Song Cover'), ('register_model_photo', 'Register Model Photo')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('cash', 'Cash'), ('test', 'Test'), ('bank', 'Bank'), ('gift_card_culture', 'Gift Card(Culture)')], max_length=256, null=True),
        ),
    ]
