# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0010_auto_20190424_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('open_event', 'Open Event'), ('test', 'Test')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_song', 'Register Song'), ('register_model_photo', 'Register Model Photo'), ('buy_song_cover', 'Buy Song Cover')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('test', 'Test'), ('cash', 'Cash'), ('gift_card_culture', 'Gift Card(Culture)'), ('bank', 'Bank')], max_length=256, null=True),
        ),
    ]
