# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0012_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_song', 'Register Song'), ('register_model_photo', 'Register Model Photo'), ('buy_song_cover', 'Buy Song Cover')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('gift_card_culture', 'Gift Card(Culture)'), ('cash', 'Cash'), ('credit', 'Credit'), ('bank', 'Bank'), ('test', 'Test')], max_length=256, null=True),
        ),
    ]
