# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0013_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('test', 'Test'), ('open_event', 'Open Event')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_model_photo', 'Register Model Photo'), ('register_song', 'Register Song'), ('buy_song_cover', 'Buy Song Cover')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('bank', 'Bank'), ('gift_card_culture', 'Gift Card(Culture)'), ('cash', 'Cash'), ('test', 'Test')], max_length=256, null=True),
        ),
    ]
