# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_song', 'Register Song'), ('buy_song_cover', 'Buy Song Cover'), ('register_model_photo', 'Register Model Photo')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('bank', 'Bank'), ('gift_card_culture', 'Gift Card(Culture)'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=256, null=True),
        ),
    ]
