# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0015_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusgem',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('open_event', 'Open Event'), ('promotion', 'Promotion')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='consumptiongem',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('register_model_photo', 'Register Model Photo'), ('buy_song_cover', 'Buy Song Cover'), ('register_song', 'Register Song')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='purchasegem',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('test', 'Test'), ('credit', 'Credit'), ('gift_card_culture', 'Gift Card(Culture)'), ('bank', 'Bank')], max_length=256, null=True),
        ),
    ]
