# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertising',
            name='priority',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='advertising_type',
            field=models.CharField(choices=[('top_video', 'TOP VIDEO'), ('top_story', 'TOP SLIDE'), ('top_music', 'TOP MUSIC'), ('top_model', 'TOP MODEL')], max_length=32, null=True),
        ),
    ]
