# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0002_auto_20190523_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='active',
            new_name='activate',
        ),
        migrations.AlterField(
            model_name='advertising',
            name='advertising_type',
            field=models.CharField(choices=[('top_video', 'TOP VIDEO'), ('top_model', 'TOP MODEL'), ('top_story', 'TOP SLIDE'), ('top_music', 'TOP MUSIC')], max_length=32, null=True),
        ),
    ]
