# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOfModeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LikeOfModeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.TextField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('female', 'Female'), ('foregin_male', 'Foregin_Male')], max_length=80, null=True)),
                ('age', models.CharField(blank=True, choices=[('10s', '10s'), ('20s', '20s'), ('40s', '40s'), ('60s', '60s'), ('50s', '50s'), ('child', 'Child'), ('30s', '30s')], max_length=20, null=True)),
                ('career', models.CharField(blank=True, choices=[('under_1year', 'Under 1 year'), ('3yr', '3yr'), ('4yr', '4yr'), ('2yr', '2yr'), ('over_6yr', 'Over 6 year'), ('5yr', '5yr')], max_length=20, null=True)),
                ('job', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('education', 'Education'), ('beauty', 'Beauty'), ('wedding', 'wedding'), ('sport', 'Sport'), ('swimsuit', 'Swimsuit'), ('finance', 'Finance'), ('fashion', 'Fashion'), ('enterprise', 'Enterprise'), ('underwear', 'Underwear'), ('hair', 'Hair'), ('drink', 'Drink')], max_length=250, null=True)),
                ('entertainment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('exhibition', 'Exhibition'), ('magazine', 'Magazine'), ('racing', 'Racing'), ('narrator_dance', 'Narrator(Dance)'), ('broadcast', 'Broadcast'), ('cf', 'CF'), ('narrator_announcement', 'Narrator(Announcement)'), ('pictorial', 'Pictorial'), ('event', 'Event')], max_length=250, null=True)),
                ('style', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cuteness', 'Cuteness'), ('pure', 'Pure'), ('bagel', 'Bagel'), ('chic', 'Chic'), ('smart', 'Smart'), ('sexy', 'Sexy'), ('tough', 'Tough')], max_length=50, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_size', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm_status', models.CharField(choices=[('approving', 'APPROVING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=10)),
                ('latest_ranking', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
