# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeler',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeler_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeofmodeler',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='likeOfModel_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeofmodeler',
            name='modeler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='likeOfModel_modeler', to='modelers.Modeler'),
        ),
        migrations.AddField(
            model_name='commentofmodeler',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentofmodeler',
            name='modeler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_modeler', to='modelers.Modeler'),
        ),
    ]
