# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0002_auto_20190420_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age',
            field=models.CharField(blank=True, choices=[('20s', '20s'), ('30s', '30s'), ('10s', '10s'), ('child', 'Child'), ('50s', '50s'), ('40s', '40s'), ('60s', '60s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('4yr', '4yr'), ('5yr', '5yr'), ('under_1year', 'Under 1 year'), ('2yr', '2yr'), ('3yr', '3yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('pendding', 'PENDDING')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('magazine', 'Magazine'), ('exhibition', 'Exhibition'), ('cf', 'CF'), ('pictorial', 'Pictorial'), ('racing', 'Racing'), ('broadcast', 'Broadcast'), ('event', 'Event'), ('narrator_announcement', 'Narrator(Announcement)'), ('narrator_dance', 'Narrator(Dance)')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('wedding', 'wedding'), ('finance', 'Finance'), ('swimsuit', 'Swimsuit'), ('hair', 'Hair'), ('education', 'Education'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('enterprise', 'Enterprise'), ('underwear', 'Underwear'), ('drink', 'Drink')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bagel', 'Bagel'), ('cuteness', 'Cuteness'), ('pure', 'Pure'), ('tough', 'Tough'), ('sexy', 'Sexy'), ('smart', 'Smart'), ('chic', 'Chic')], max_length=50, null=True),
        ),
    ]
