# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0003_auto_20190420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age',
            field=models.CharField(blank=True, choices=[('30s', '30s'), ('50s', '50s'), ('20s', '20s'), ('10s', '10s'), ('40s', '40s'), ('60s', '60s'), ('child', 'Child')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('3yr', '3yr'), ('5yr', '5yr'), ('under_1year', 'Under 1 year'), ('2yr', '2yr'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('approving', 'APPROVING')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cf', 'CF'), ('narrator_announcement', 'Narrator(Announcement)'), ('magazine', 'Magazine'), ('broadcast', 'Broadcast'), ('racing', 'Racing'), ('pictorial', 'Pictorial'), ('event', 'Event'), ('narrator_dance', 'Narrator(Dance)'), ('exhibition', 'Exhibition')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('not_specified', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('foregin_female', 'Foregin_Female')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fashion', 'Fashion'), ('underwear', 'Underwear'), ('swimsuit', 'Swimsuit'), ('wedding', 'wedding'), ('enterprise', 'Enterprise'), ('drink', 'Drink'), ('beauty', 'Beauty'), ('sport', 'Sport'), ('finance', 'Finance'), ('education', 'Education'), ('hair', 'Hair')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tough', 'Tough'), ('sexy', 'Sexy'), ('bagel', 'Bagel'), ('cuteness', 'Cuteness'), ('chic', 'Chic'), ('smart', 'Smart'), ('pure', 'Pure')], max_length=50, null=True),
        ),
    ]
