# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0005_auto_20190424_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeler',
            name='body_size',
        ),
        migrations.AlterField(
            model_name='modeler',
            name='age',
            field=models.CharField(blank=True, choices=[('50s', '50s'), ('10s', '10s'), ('20s', '20s'), ('30s', '30s'), ('60s', '60s'), ('child', 'Child'), ('40s', '40s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('5yr', '5yr'), ('3yr', '3yr'), ('4yr', '4yr'), ('2yr', '2yr'), ('under_1year', 'Under 1 year'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('ready', 'READY'), ('rejected', 'REJECTED'), ('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('approved', 'APPROVED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('broadcast', 'Broadcast'), ('pictorial', 'Pictorial'), ('magazine', 'Magazine'), ('narrator_dance', 'Narrator(Dance)'), ('cf', 'CF'), ('narrator_announcement', 'Narrator(Announcement)'), ('racing', 'Racing'), ('event', 'Event'), ('exhibition', 'Exhibition')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('female', 'Female'), ('male', 'Male')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('drink', 'Drink'), ('hair', 'Hair'), ('beauty', 'Beauty'), ('sport', 'Sport'), ('wedding', 'wedding'), ('finance', 'Finance'), ('swimsuit', 'Swimsuit'), ('education', 'Education'), ('enterprise', 'Enterprise'), ('underwear', 'Underwear'), ('fashion', 'Fashion')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bagel', 'Bagel'), ('cuteness', 'Cuteness'), ('pure', 'Pure'), ('smart', 'Smart'), ('sexy', 'Sexy'), ('chic', 'Chic'), ('tough', 'Tough')], max_length=64, null=True),
        ),
    ]
