# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0006_auto_20190424_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeler',
            old_name='body_size_bust',
            new_name='bust',
        ),
        migrations.RenameField(
            model_name='modeler',
            old_name='body_size_hip',
            new_name='hip',
        ),
        migrations.RenameField(
            model_name='modeler',
            old_name='body_size_wiast',
            new_name='wiast',
        ),
        migrations.AlterField(
            model_name='modeler',
            name='age',
            field=models.CharField(blank=True, choices=[('40s', '40s'), ('20s', '20s'), ('30s', '30s'), ('50s', '50s'), ('child', 'Child'), ('60s', '60s'), ('10s', '10s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('3yr', '3yr'), ('2yr', '2yr'), ('5yr', '5yr'), ('under_1year', 'Under 1 year'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('broadcast', 'Broadcast'), ('cf', 'CF'), ('narrator_announcement', 'Narrator(Announcement)'), ('pictorial', 'Pictorial'), ('racing', 'Racing'), ('event', 'Event'), ('magazine', 'Magazine'), ('exhibition', 'Exhibition'), ('narrator_dance', 'Narrator(Dance)')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('not_specified', 'Not specified'), ('female', 'Female')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fashion', 'Fashion'), ('hair', 'Hair'), ('beauty', 'Beauty'), ('wedding', 'wedding'), ('underwear', 'Underwear'), ('sport', 'Sport'), ('enterprise', 'Enterprise'), ('education', 'Education'), ('finance', 'Finance'), ('swimsuit', 'Swimsuit'), ('drink', 'Drink')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chic', 'Chic'), ('cuteness', 'Cuteness'), ('pure', 'Pure'), ('sexy', 'Sexy'), ('bagel', 'Bagel'), ('smart', 'Smart'), ('tough', 'Tough')], max_length=64, null=True),
        ),
    ]
