# Generated by Django 2.0.13 on 2019-04-24 11:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0007_auto_20190424_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeler',
            name='age',
        ),
        migrations.AddField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('30s', '30s'), ('50s', '50s'), ('40s', '40s'), ('20s', '20s'), ('60s', '60s'), ('child', 'Child'), ('10s', '10s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('over_6yr', 'Over 6 year'), ('4yr', '4yr'), ('2yr', '2yr'), ('3yr', '3yr'), ('under_1year', 'Under 1 year'), ('5yr', '5yr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('pendding', 'PENDDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('ready', 'READY')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cf', 'CF'), ('racing', 'Racing'), ('event', 'Event'), ('magazine', 'Magazine'), ('narrator_announcement', 'Narrator(Announcement)'), ('pictorial', 'Pictorial'), ('broadcast', 'Broadcast'), ('narrator_dance', 'Narrator(Dance)'), ('exhibition', 'Exhibition')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('foregin_female', 'Foregin_Female'), ('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('not_specified', 'Not specified')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('swimsuit', 'Swimsuit'), ('wedding', 'wedding'), ('fashion', 'Fashion'), ('underwear', 'Underwear'), ('sport', 'Sport'), ('beauty', 'Beauty'), ('enterprise', 'Enterprise'), ('drink', 'Drink'), ('hair', 'Hair'), ('finance', 'Finance'), ('education', 'Education')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chic', 'Chic'), ('smart', 'Smart'), ('cuteness', 'Cuteness'), ('pure', 'Pure'), ('bagel', 'Bagel'), ('sexy', 'Sexy'), ('tough', 'Tough')], max_length=64, null=True),
        ),
    ]
