# Generated by Django 2.0.13 on 2019-04-24 11:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0008_auto_20190424_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeler',
            name='age',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('2yr', '2yr'), ('3yr', '3yr'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year'), ('5yr', '5yr'), ('under_1year', 'Under 1 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('30s', '30s'), ('10s', '10s'), ('child', 'Child'), ('50s', '50s'), ('60s', '60s'), ('20s', '20s'), ('40s', '40s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('2yr', '2yr'), ('3yr', '3yr'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year'), ('5yr', '5yr'), ('under_1year', 'Under 1 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('approved', 'APPROVED'), ('ready', 'READY')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('narrator_dance', 'Narrator(Dance)'), ('event', 'Event'), ('pictorial', 'Pictorial'), ('narrator_announcement', 'Narrator(Announcement)'), ('broadcast', 'Broadcast'), ('exhibition', 'Exhibition'), ('cf', 'CF'), ('racing', 'Racing'), ('magazine', 'Magazine')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('not_specified', 'Not specified'), ('foregin_male', 'Foregin_Male'), ('foregin_female', 'Foregin_Female'), ('male', 'Male')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('underwear', 'Underwear'), ('hair', 'Hair'), ('education', 'Education'), ('beauty', 'Beauty'), ('enterprise', 'Enterprise'), ('drink', 'Drink'), ('sport', 'Sport'), ('wedding', 'wedding'), ('swimsuit', 'Swimsuit'), ('finance', 'Finance'), ('fashion', 'Fashion')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tough', 'Tough'), ('sexy', 'Sexy'), ('smart', 'Smart'), ('chic', 'Chic'), ('bagel', 'Bagel'), ('pure', 'Pure'), ('cuteness', 'Cuteness')], max_length=64, null=True),
        ),
    ]
