# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0009_auto_20190424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('10s', '10s'), ('child', 'Child'), ('40s', '40s'), ('20s', '20s'), ('30s', '30s'), ('60s', '60s'), ('50s', '50s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'blood_type_a'), ('O', 'blood_type_o'), ('AB', 'blood_type_ab'), ('B', 'blood_type_b'), ('ETC', 'blood_type_etc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('2yr', '2yr'), ('3yr', '3yr'), ('5yr', '5yr'), ('under_1year', 'Under 1 year'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('ready', 'READY'), ('approved', 'APPROVED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('exhibition', 'Exhibition'), ('narrator_announcement', 'Narrator(Announcement)'), ('event', 'Event'), ('pictorial', 'Pictorial'), ('magazine', 'Magazine'), ('narrator_dance', 'Narrator(Dance)'), ('racing', 'Racing'), ('broadcast', 'Broadcast'), ('cf', 'CF')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not specified'), ('foregin_female', 'Foregin_Female')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('drink', 'Drink'), ('beauty', 'Beauty'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('hair', 'Hair'), ('swimsuit', 'Swimsuit'), ('sport', 'Sport'), ('underwear', 'Underwear'), ('enterprise', 'Enterprise'), ('wedding', 'wedding'), ('education', 'Education')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('smart', 'Smart'), ('sexy', 'Sexy'), ('tough', 'Tough'), ('bagel', 'Bagel'), ('cuteness', 'Cuteness'), ('chic', 'Chic'), ('pure', 'Pure')], max_length=64, null=True),
        ),
    ]
