# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0011_auto_20190424_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeler',
            name='birth_day',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='modeler',
            name='birth_month',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='modeler',
            name='birth_year',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('40s', '40s'), ('20s', '20s'), ('10s', '10s'), ('50s', '50s'), ('60s', '60s'), ('30s', '30s'), ('child', 'Child')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('blood_type_ab', 'AB'), ('blood_type_etc', 'ETC'), ('blood_type_b', 'B'), ('blood_type_o', 'O'), ('blood_type_a', 'A')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('3yr', '3yr'), ('2yr', '2yr'), ('under_1year', 'Under 1 year'), ('5yr', '5yr'), ('4yr', '4yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('approving', 'APPROVING'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('event', 'Event'), ('narrator_dance', 'Narrator(Dance)'), ('exhibition', 'Exhibition'), ('cf', 'CF'), ('broadcast', 'Broadcast'), ('magazine', 'Magazine'), ('pictorial', 'Pictorial'), ('narrator_announcement', 'Narrator(Announcement)'), ('racing', 'Racing')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('female', 'Female'), ('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('beauty', 'Beauty'), ('education', 'Education'), ('wedding', 'wedding'), ('drink', 'Drink'), ('sport', 'Sport'), ('swimsuit', 'Swimsuit'), ('enterprise', 'Enterprise'), ('hair', 'Hair'), ('fashion', 'Fashion'), ('underwear', 'Underwear'), ('finance', 'Finance')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pure', 'Pure'), ('tough', 'Tough'), ('sexy', 'Sexy'), ('bagel', 'Bagel'), ('chic', 'Chic'), ('smart', 'Smart'), ('cuteness', 'Cuteness')], max_length=64, null=True),
        ),
    ]
