# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0012_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('40s', '40s'), ('10s', '10s'), ('20s', '20s'), ('child', 'Child'), ('30s', '30s'), ('60s', '60s'), ('50s', '50s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('blood_type_b', 'B'), ('blood_type_ab', 'AB'), ('blood_type_a', 'A'), ('blood_type_etc', 'ETC'), ('blood_type_o', 'O')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('under_1year', 'Under 1 year'), ('over_6yr', 'Over 6 year'), ('5yr', '5yr'), ('2yr', '2yr'), ('4yr', '4yr'), ('3yr', '3yr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('ready', 'READY'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('racing', 'Racing'), ('pictorial', 'Pictorial'), ('magazine', 'Magazine'), ('exhibition', 'Exhibition'), ('event', 'Event'), ('broadcast', 'Broadcast'), ('narrator_announcement', 'Narrator(Announcement)'), ('narrator_dance', 'Narrator(Dance)'), ('cf', 'CF')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('female', 'Female')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('swimsuit', 'Swimsuit'), ('wedding', 'wedding'), ('hair', 'Hair'), ('enterprise', 'Enterprise'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('finance', 'Finance'), ('education', 'Education'), ('sport', 'Sport'), ('underwear', 'Underwear'), ('drink', 'Drink')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cuteness', 'Cuteness'), ('tough', 'Tough'), ('bagel', 'Bagel'), ('smart', 'Smart'), ('pure', 'Pure'), ('sexy', 'Sexy'), ('chic', 'Chic')], max_length=64, null=True),
        ),
    ]
