# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0013_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeofmodeler',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likeofmodeler',
            name='modeler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like_modeler', to='modelers.Modeler'),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('10s', '10s'), ('20s', '20s'), ('40s', '40s'), ('60s', '60s'), ('50s', '50s'), ('child', 'Child'), ('30s', '30s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('blood_type_b', 'B-TYPE'), ('blood_type_ab', 'AB-TYPE'), ('blood_type_etc', 'ETC'), ('blood_type_a', 'A-TYPE'), ('blood_type_o', 'O-TYPE')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('2yr', '2yr'), ('3yr', '3yr'), ('under_1year', 'Under 1 year'), ('over_6yr', 'Over 6 year'), ('4yr', '4yr'), ('5yr', '5yr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cf', 'CF'), ('narrator_dance', 'Narrator(Dance)'), ('magazine', 'Magazine'), ('narrator_announcement', 'Narrator(Announcement)'), ('broadcast', 'Broadcast'), ('pictorial', 'Pictorial'), ('racing', 'Racing'), ('exhibition', 'Exhibition'), ('event', 'Event')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('foregin_female', 'Foregin_Female'), ('female', 'Female'), ('not_specified', 'Not specified')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('swimsuit', 'Swimsuit'), ('finance', 'Finance'), ('wedding', 'wedding'), ('enterprise', 'Enterprise'), ('hair', 'Hair'), ('education', 'Education'), ('drink', 'Drink'), ('sport', 'Sport'), ('underwear', 'Underwear'), ('beauty', 'Beauty'), ('fashion', 'Fashion')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sexy', 'Sexy'), ('cuteness', 'Cuteness'), ('pure', 'Pure'), ('chic', 'Chic'), ('smart', 'Smart'), ('bagel', 'Bagel'), ('tough', 'Tough')], max_length=64, null=True),
        ),
    ]
