# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('50s', '50s'), ('10s', '10s'), ('60s', '60s'), ('20s', '20s'), ('child', 'Child'), ('40s', '40s'), ('30s', '30s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('blood_type_b', 'B-TYPE'), ('blood_type_a', 'A-TYPE'), ('blood_type_ab', 'AB-TYPE'), ('blood_type_o', 'O-TYPE'), ('blood_type_etc', 'ETC')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('5yr', '5yr'), ('4yr', '4yr'), ('2yr', '2yr'), ('over_6yr', 'Over 6 year'), ('under_1year', 'Under 1 year'), ('3yr', '3yr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pictorial', 'Pictorial'), ('broadcast', 'Broadcast'), ('racing', 'Racing'), ('narrator_announcement', 'Narrator(Announcement)'), ('exhibition', 'Exhibition'), ('magazine', 'Magazine'), ('narrator_dance', 'Narrator(Dance)'), ('event', 'Event'), ('cf', 'CF')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('foregin_male', 'Foregin_Male')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('drink', 'Drink'), ('hair', 'Hair'), ('wedding', 'wedding'), ('sport', 'Sport'), ('finance', 'Finance'), ('beauty', 'Beauty'), ('education', 'Education'), ('fashion', 'Fashion'), ('swimsuit', 'Swimsuit'), ('enterprise', 'Enterprise'), ('underwear', 'Underwear')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cuteness', 'Cuteness'), ('chic', 'Chic'), ('sexy', 'Sexy'), ('bagel', 'Bagel'), ('tough', 'Tough'), ('pure', 'Pure'), ('smart', 'Smart')], max_length=64, null=True),
        ),
    ]
