# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelers', '0015_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeler',
            name='age_range',
            field=models.CharField(blank=True, choices=[('50s', '50s'), ('30s', '30s'), ('60s', '60s'), ('40s', '40s'), ('child', 'Child'), ('10s', '10s'), ('20s', '20s')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('blood_type_ab', 'AB-TYPE'), ('blood_type_etc', 'ETC'), ('blood_type_b', 'B-TYPE'), ('blood_type_a', 'A-TYPE'), ('blood_type_o', 'O-TYPE')], max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='career',
            field=models.CharField(blank=True, choices=[('3yr', '3yr'), ('4yr', '4yr'), ('5yr', '5yr'), ('under_1year', 'Under 1 year'), ('2yr', '2yr'), ('over_6yr', 'Over 6 year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('ready', 'READY'), ('completed', 'COMPLETED')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='entertainment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('event', 'Event'), ('cf', 'CF'), ('narrator_announcement', 'Narrator(Announcement)'), ('broadcast', 'Broadcast'), ('magazine', 'Magazine'), ('exhibition', 'Exhibition'), ('pictorial', 'Pictorial'), ('racing', 'Racing'), ('narrator_dance', 'Narrator(Dance)')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('female', 'Female'), ('male', 'Male'), ('not_specified', 'Not specified'), ('foregin_male', 'Foregin_Male')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='job',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hair', 'Hair'), ('swimsuit', 'Swimsuit'), ('finance', 'Finance'), ('drink', 'Drink'), ('underwear', 'Underwear'), ('sport', 'Sport'), ('wedding', 'wedding'), ('beauty', 'Beauty'), ('fashion', 'Fashion'), ('enterprise', 'Enterprise'), ('education', 'Education')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='modeler',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chic', 'Chic'), ('bagel', 'Bagel'), ('sexy', 'Sexy'), ('pure', 'Pure'), ('cuteness', 'Cuteness'), ('smart', 'Smart'), ('tough', 'Tough')], max_length=64, null=True),
        ),
    ]
