# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='copyright_id', max_length=64)),
                ('copyright_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelPhotoCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_chain_id', models.CharField(blank=True, max_length=256)),
                ('block_chain_txid', models.CharField(blank=True, max_length=256)),
                ('confirm_status', models.CharField(choices=[('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_chain_id', models.CharField(blank=True, max_length=256)),
                ('block_chain_txid', models.CharField(blank=True, max_length=256)),
                ('confirm_status', models.CharField(choices=[('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
