# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copyrights', '0001_initial'),
        ('modelphotos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccopyright',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musiccopyright',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs.Song'),
        ),
        migrations.AddField(
            model_name='modelphotocopyright',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelphotocopyright',
            name='modelphoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelphotos.ModelPhoto'),
        ),
    ]
