# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0002_auto_20190420_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED')], default='ready', max_length=254),
        ),
    ]
