# Generated by Django 2.0.13 on 2019-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0004_auto_20190420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('ready', 'READY')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('ready', 'READY')], default='ready', max_length=254),
        ),
    ]
