# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0005_auto_20190424_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
    ]
