# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0006_auto_20190424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
    ]
