# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0013_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED')], default='ready', max_length=254),
        ),
    ]
