# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyrights', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphotocopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
        migrations.AlterField(
            model_name='musiccopyright',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=254),
        ),
    ]
