# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0002_musician_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.Musician'),
        ),
        migrations.AddField(
            model_name='playofsong',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playofsong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='play', to='songs.Song'),
        ),
        migrations.AddField(
            model_name='likeofsong',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeofsong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like', to='songs.Song'),
        ),
        migrations.AddField(
            model_name='downloadofsong',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadofsong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='download', to='songs.Song'),
        ),
        migrations.AddField(
            model_name='coverimage',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='song_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentofsong',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentofsong',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='songs.Song'),
        ),
    ]
