# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20190420_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('over_10year', 'Over 10 year'), ('_5yr', '5yr'), ('_2yr', '2yr'), ('_4yr', '4yr'), ('_3yr', '3yr'), ('under_1year', 'Under 1 year'), ('_6yr_10yr', '6yr ~ 10yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('pendding', 'PENDDING')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('trot', 'Trot'), ('rock_band', 'Rock/Band'), ('rnb_soul', 'R&B/Soul'), ('rap_hip_hop', 'Rap/Hip-hop'), ('jazz', 'Jazz'), ('folk_blues', 'Folk/Blues'), ('ballad', 'Ballad'), ('dance', 'Dance')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('trance', 'TRANCE'), ('cm', 'CM'), ('ccm', 'CCM'), ('edm', 'EDM'), ('ost', 'OST'), ('thecno', 'THECNO'), ('rave', 'RAVE'), ('carol', 'CAROL'), ('club', 'CLUB')], max_length=254),
        ),
    ]
