# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20190420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('over_10year', 'Over 10 year'), ('under_1year', 'Under 1 year'), ('_2yr', '2yr'), ('_3yr', '3yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr'), ('_4yr', '4yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('approving', 'APPROVING')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('dance', 'Dance'), ('jazz', 'Jazz'), ('trot', 'Trot'), ('folk_blues', 'Folk/Blues'), ('rock_band', 'Rock/Band'), ('rap_hip_hop', 'Rap/Hip-hop'), ('ballad', 'Ballad'), ('rnb_soul', 'R&B/Soul')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('edm', 'EDM'), ('ccm', 'CCM'), ('carol', 'CAROL'), ('thecno', 'THECNO'), ('club', 'CLUB'), ('ost', 'OST'), ('rave', 'RAVE'), ('trance', 'TRANCE'), ('cm', 'CM')], max_length=254),
        ),
    ]
