# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20190424_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_5yr', '5yr'), ('under_1year', 'Under 1 year'), ('_3yr', '3yr'), ('_2yr', '2yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_4yr', '4yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('ready', 'READY'), ('rejected', 'REJECTED'), ('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('approved', 'APPROVED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('dance', 'Dance'), ('ballad', 'Ballad'), ('jazz', 'Jazz'), ('rock_band', 'Rock/Band'), ('trot', 'Trot'), ('folk_blues', 'Folk/Blues'), ('rap_hip_hop', 'Rap/Hip-hop'), ('rnb_soul', 'R&B/Soul')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('thecno', 'THECNO'), ('edm', 'EDM'), ('carol', 'CAROL'), ('club', 'CLUB'), ('ost', 'OST'), ('ccm', 'CCM'), ('cm', 'CM'), ('rave', 'RAVE'), ('trance', 'TRANCE')], max_length=254),
        ),
    ]
