# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20190424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_5yr', '5yr'), ('_2yr', '2yr'), ('under_1year', 'Under 1 year'), ('_4yr', '4yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_3yr', '3yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rnb_soul', 'R&B/Soul'), ('jazz', 'Jazz'), ('rock_band', 'Rock/Band'), ('folk_blues', 'Folk/Blues'), ('rap_hip_hop', 'Rap/Hip-hop'), ('trot', 'Trot'), ('ballad', 'Ballad'), ('dance', 'Dance')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('ost', 'OST'), ('trance', 'TRANCE'), ('edm', 'EDM'), ('ccm', 'CCM'), ('carol', 'CAROL'), ('cm', 'CM'), ('thecno', 'THECNO'), ('club', 'CLUB'), ('rave', 'RAVE')], max_length=254),
        ),
    ]
