# Generated by Django 2.0.13 on 2019-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20190424_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_4yr', '4yr'), ('under_1year', 'Under 1 year'), ('over_10year', 'Over 10 year'), ('_3yr', '3yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_2yr', '2yr'), ('_5yr', '5yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('pendding', 'PENDDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('ready', 'READY')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('ballad', 'Ballad'), ('trot', 'Trot'), ('rock_band', 'Rock/Band'), ('rnb_soul', 'R&B/Soul'), ('folk_blues', 'Folk/Blues'), ('rap_hip_hop', 'Rap/Hip-hop'), ('dance', 'Dance')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('carol', 'CAROL'), ('rave', 'RAVE'), ('cm', 'CM'), ('thecno', 'THECNO'), ('trance', 'TRANCE'), ('edm', 'EDM'), ('ost', 'OST'), ('ccm', 'CCM'), ('club', 'CLUB')], max_length=254),
        ),
    ]
