# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20190424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_4yr', '4yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_3yr', '3yr'), ('under_1year', 'Under 1 year'), ('over_10year', 'Over 10 year'), ('_2yr', '2yr'), ('_5yr', '5yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('ready', 'READY'), ('approved', 'APPROVED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('ballad', 'Ballad'), ('folk_blues', 'Folk/Blues'), ('rap_hip_hop', 'Rap/Hip-hop'), ('jazz', 'Jazz'), ('trot', 'Trot'), ('dance', 'Dance'), ('rock_band', 'Rock/Band'), ('rnb_soul', 'R&B/Soul')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('club', 'CLUB'), ('carol', 'CAROL'), ('ccm', 'CCM'), ('cm', 'CM'), ('ost', 'OST'), ('trance', 'TRANCE'), ('edm', 'EDM'), ('rave', 'RAVE'), ('thecno', 'THECNO')], max_length=254),
        ),
    ]
