# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20190424_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('under_1year', 'Under 1 year'), ('_4yr', '4yr'), ('_3yr', '3yr'), ('over_10year', 'Over 10 year'), ('_2yr', '2yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('rejected', 'REJECTED'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('approved', 'APPROVED'), ('approving', 'APPROVING')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rnb_soul', 'R&B/Soul'), ('rock_band', 'Rock/Band'), ('jazz', 'Jazz'), ('trot', 'Trot'), ('ballad', 'Ballad'), ('dance', 'Dance'), ('folk_blues', 'Folk/Blues'), ('rap_hip_hop', 'Rap/Hip-hop')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('edm', 'EDM'), ('ost', 'OST'), ('carol', 'CAROL'), ('rave', 'RAVE'), ('club', 'CLUB'), ('cm', 'CM'), ('thecno', 'THECNO'), ('trance', 'TRANCE'), ('ccm', 'CCM')], max_length=254),
        ),
    ]
