# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_auto_20190424_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_4yr', '4yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('under_1year', 'Under 1 year'), ('_5yr', '5yr'), ('over_10year', 'Over 10 year'), ('_3yr', '3yr'), ('_2yr', '2yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('rejected', 'REJECTED'), ('approving', 'APPROVING'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('ballad', 'Ballad'), ('rap_hip_hop', 'Rap/Hip-hop'), ('jazz', 'Jazz'), ('rnb_soul', 'R&B/Soul'), ('folk_blues', 'Folk/Blues'), ('dance', 'Dance'), ('rock_band', 'Rock/Band'), ('trot', 'Trot')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('rave', 'RAVE'), ('ost', 'OST'), ('cm', 'CM'), ('carol', 'CAROL'), ('trance', 'TRANCE'), ('club', 'CLUB'), ('ccm', 'CCM'), ('thecno', 'THECNO'), ('edm', 'EDM')], max_length=254),
        ),
    ]
