# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_3yr', '3yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr'), ('under_1year', 'Under 1 year'), ('over_10year', 'Over 10 year'), ('_2yr', '2yr'), ('_4yr', '4yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('ready', 'READY'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rnb_soul', 'R&B/Soul'), ('rap_hip_hop', 'Rap/Hip-hop'), ('jazz', 'Jazz'), ('dance', 'Dance'), ('trot', 'Trot'), ('ballad', 'Ballad'), ('folk_blues', 'Folk/Blues'), ('rock_band', 'Rock/Band')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('trance', 'TRANCE'), ('rave', 'RAVE'), ('cm', 'CM'), ('ost', 'OST'), ('ccm', 'CCM'), ('thecno', 'THECNO'), ('carol', 'CAROL'), ('club', 'CLUB'), ('edm', 'EDM')], max_length=254),
        ),
    ]
