# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_3yr', '3yr'), ('_2yr', '2yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr'), ('under_1year', 'Under 1 year'), ('_4yr', '4yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('ballad', 'Ballad'), ('rock_band', 'Rock/Band'), ('dance', 'Dance'), ('folk_blues', 'Folk/Blues'), ('jazz', 'Jazz'), ('rap_hip_hop', 'Rap/Hip-hop'), ('trot', 'Trot'), ('rnb_soul', 'R&B/Soul')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('ccm', 'CCM'), ('edm', 'EDM'), ('club', 'CLUB'), ('carol', 'CAROL'), ('trance', 'TRANCE'), ('thecno', 'THECNO'), ('rave', 'RAVE'), ('ost', 'OST'), ('cm', 'CM')], max_length=254),
        ),
    ]
