# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_4yr', '4yr'), ('_5yr', '5yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('under_1year', 'Under 1 year'), ('_3yr', '3yr'), ('_2yr', '2yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('ballad', 'Ballad'), ('trot', 'Trot'), ('rnb_soul', 'R&B/Soul'), ('rap_hip_hop', 'Rap/Hip-hop'), ('folk_blues', 'Folk/Blues'), ('jazz', 'Jazz'), ('dance', 'Dance'), ('rock_band', 'Rock/Band')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('cm', 'CM'), ('ost', 'OST'), ('thecno', 'THECNO'), ('rave', 'RAVE'), ('club', 'CLUB'), ('carol', 'CAROL'), ('edm', 'EDM'), ('ccm', 'CCM'), ('trance', 'TRANCE')], max_length=254),
        ),
    ]
