# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='career',
            field=models.CharField(choices=[('_4yr', '4yr'), ('under_1year', 'Under 1 year'), ('_5yr', '5yr'), ('over_10year', 'Over 10 year'), ('_6yr_10yr', '6yr ~ 10yr'), ('_2yr', '2yr'), ('_3yr', '3yr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('ready', 'READY'), ('completed', 'COMPLETED')], default='ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rap_hip_hop', 'Rap/Hip-hop'), ('jazz', 'Jazz'), ('ballad', 'Ballad'), ('trot', 'Trot'), ('dance', 'Dance'), ('folk_blues', 'Folk/Blues'), ('rnb_soul', 'R&B/Soul'), ('rock_band', 'Rock/Band')], max_length=254),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre_detail',
            field=models.CharField(choices=[('rave', 'RAVE'), ('ccm', 'CCM'), ('trance', 'TRANCE'), ('edm', 'EDM'), ('thecno', 'THECNO'), ('cm', 'CM'), ('ost', 'OST'), ('carol', 'CAROL'), ('club', 'CLUB')], max_length=254),
        ),
    ]
