# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('nickname', models.TextField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('career', models.CharField(choices=[('under_1year', 'Under 1 year'), ('_3yr', '3yr'), ('_2yr', '2yr'), ('_5yr', '5yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('over_10year', 'Over 10 year'), ('_4yr', '4yr')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
