# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musician_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
