# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_musician_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(choices=[('over_10year', 'Over 10 year'), ('_5yr', '5yr'), ('_2yr', '2yr'), ('_4yr', '4yr'), ('_3yr', '3yr'), ('under_1year', 'Under 1 year'), ('_6yr_10yr', '6yr ~ 10yr')], max_length=20),
        ),
    ]
