# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_auto_20190420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(choices=[('over_10year', 'Over 10 year'), ('under_1year', 'Under 1 year'), ('_2yr', '2yr'), ('_3yr', '3yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr'), ('_4yr', '4yr')], max_length=20),
        ),
    ]
