# Generated by Django 2.0.13 on 2019-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_auto_20190420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(blank=True, choices=[('_2yr', '2yr'), ('under_1year', 'Under 1 year'), ('over_10year', 'Over 10 year'), ('_5yr', '5yr'), ('_3yr', '3yr'), ('_4yr', '4yr'), ('_6yr_10yr', '6yr ~ 10yr')], max_length=20),
        ),
    ]
