# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_auto_20190424_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(blank=True, choices=[('_5yr', '5yr'), ('under_1year', 'Under 1 year'), ('_3yr', '3yr'), ('_2yr', '2yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_4yr', '4yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
    ]
