# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0010_auto_20190424_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(blank=True, choices=[('under_1year', 'Under 1 year'), ('_4yr', '4yr'), ('_3yr', '3yr'), ('over_10year', 'Over 10 year'), ('_2yr', '2yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('_5yr', '5yr')], max_length=20),
        ),
    ]
