# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(blank=True, choices=[('_4yr', '4yr'), ('_5yr', '5yr'), ('_6yr_10yr', '6yr ~ 10yr'), ('under_1year', 'Under 1 year'), ('_3yr', '3yr'), ('_2yr', '2yr'), ('over_10year', 'Over 10 year')], max_length=20),
        ),
    ]
