# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0015_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='career',
            field=models.CharField(blank=True, choices=[('_4yr', '4yr'), ('under_1year', 'Under 1 year'), ('_5yr', '5yr'), ('over_10year', 'Over 10 year'), ('_6yr_10yr', '6yr ~ 10yr'), ('_2yr', '2yr'), ('_3yr', '3yr')], max_length=20),
        ),
    ]
