# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.db import migrations, models
import gemtown.modelphotos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_type', models.CharField(blank=True, choices=[('cover', 'COVER'), ('etc', 'ETC'), ('full', 'FULL'), ('half', 'HALF')], max_length=256)),
                ('file', models.ImageField(upload_to=gemtown.modelphotos.models.ModelPhoto.upload_file_name)),
                ('confirm_status', models.CharField(choices=[('approving', 'APPROVING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('ready', 'READY'), ('pendding', 'PENDDING')], default='ready', max_length=20)),
                ('contents_hash', models.CharField(blank=True, max_length=256)),
                ('blockchain_id', models.CharField(blank=True, max_length=256)),
                ('blockchain_txid', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
