# Generated by Django 2.0.13 on 2019-04-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelphotos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelers', '0002_auto_20190420_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelphoto',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelphoto',
            name='modeler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modelers.Modeler'),
        ),
    ]
