# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0002_auto_20190420_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('pendding', 'PENDDING')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('half', 'HALF'), ('full', 'FULL'), ('cover', 'COVER'), ('etc', 'ETC')], max_length=256),
        ),
    ]
