# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0003_auto_20190420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('ready', 'READY'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('approving', 'APPROVING')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('half', 'HALF'), ('full', 'FULL'), ('etc', 'ETC'), ('cover', 'COVER')], max_length=256),
        ),
    ]
