# Generated by Django 2.0.13 on 2019-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0004_auto_20190420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('completed', 'COMPLETED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('etc', 'ETC'), ('full', 'FULL'), ('cover', 'COVER'), ('half', 'HALF')], max_length=256),
        ),
    ]
