# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0006_auto_20190424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('full', 'FULL'), ('cover', 'COVER'), ('half', 'HALF'), ('etc', 'ETC')], max_length=256),
        ),
    ]
