# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0009_auto_20190424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('ready', 'READY'), ('approved', 'APPROVED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('cover', 'COVER'), ('etc', 'ETC'), ('full', 'FULL'), ('half', 'HALF')], max_length=256),
        ),
    ]
