# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0013_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('approving', 'APPROVING'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('ready', 'READY'), ('pendding', 'PENDDING'), ('approved', 'APPROVED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('half', 'HALF'), ('etc', 'ETC'), ('cover', 'COVER'), ('full', 'FULL')], max_length=256),
        ),
    ]
