# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0014_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('ready', 'READY'), ('pendding', 'PENDDING'), ('completed', 'COMPLETED'), ('approving', 'APPROVING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('half', 'HALF'), ('cover', 'COVER'), ('full', 'FULL'), ('etc', 'ETC')], max_length=256),
        ),
    ]
