# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelphotos', '0015_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelphoto',
            name='confirm_status',
            field=models.CharField(choices=[('pendding', 'PENDDING'), ('approving', 'APPROVING'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('ready', 'READY'), ('completed', 'COMPLETED')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelphoto',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('half', 'HALF'), ('etc', 'ETC'), ('cover', 'COVER'), ('full', 'FULL')], max_length=256),
        ),
    ]
