# Generated by Django 2.0.13 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('hk', 'Hong Kong'), ('cn', 'China'), ('sg', 'Singapore'), ('id', 'Indonesia'), ('kr', 'Korea'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('hk', 'Hong Kong'), ('cn', 'China'), ('sg', 'Singapore'), ('id', 'Indonesia'), ('kr', 'Korea'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('artist', 'Artist'), ('company', 'Company')], default='nomal', max_length=80),
        ),
    ]
