# Generated by Django 2.0.13 on 2019-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('jp', 'Japan'), ('kr', 'Korea'), ('id', 'Indonesia'), ('sg', 'Singapore'), ('vn', 'Viet Nam'), ('hk', 'Hong Kong'), ('us', 'United States of America')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('not_specified', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('foregin_female', 'Foregin_Female')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('jp', 'Japan'), ('kr', 'Korea'), ('id', 'Indonesia'), ('sg', 'Singapore'), ('vn', 'Viet Nam'), ('hk', 'Hong Kong'), ('us', 'United States of America')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('company', 'Company'), ('artist', 'Artist')], default='nomal', max_length=80),
        ),
    ]
