# Generated by Django 2.0.13 on 2019-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States of America'), ('sg', 'Singapore'), ('kr', 'Korea'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('id', 'Indonesia'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('not_specified', 'Not specified'), ('foregin_male', 'Foregin_Male'), ('foregin_female', 'Foregin_Female')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States of America'), ('sg', 'Singapore'), ('kr', 'Korea'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('id', 'Indonesia'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('artist', 'Artist'), ('common', 'Common')], default='nomal', max_length=80),
        ),
    ]
