# Generated by Django 2.0.13 on 2019-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190424_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('kr', 'Korea'), ('vn', 'Viet Nam'), ('id', 'Indonesia'), ('jp', 'Japan'), ('sg', 'Singapore'), ('hk', 'Hong Kong'), ('us', 'United States of America'), ('cn', 'China')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('female', 'Female'), ('male', 'Male')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('kr', 'Korea'), ('vn', 'Viet Nam'), ('id', 'Indonesia'), ('jp', 'Japan'), ('sg', 'Singapore'), ('hk', 'Hong Kong'), ('us', 'United States of America'), ('cn', 'China')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('company', 'Company'), ('common', 'Common')], default='nomal', max_length=80),
        ),
    ]
