# Generated by Django 2.0.13 on 2019-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('kr', 'Korea'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('sg', 'Singapore'), ('us', 'United States of America'), ('cn', 'China')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('not_specified', 'Not specified'), ('female', 'Female')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('kr', 'Korea'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('sg', 'Singapore'), ('us', 'United States of America'), ('cn', 'China')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('common', 'Common'), ('company', 'Company')], default='nomal', max_length=80),
        ),
    ]
