# Generated by Django 2.0.13 on 2019-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190424_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('hk', 'Hong Kong'), ('cn', 'China'), ('kr', 'Korea'), ('sg', 'Singapore'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('foregin_female', 'Foregin_Female'), ('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('not_specified', 'Not specified')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('hk', 'Hong Kong'), ('cn', 'China'), ('kr', 'Korea'), ('sg', 'Singapore'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('common', 'Common'), ('artist', 'Artist')], default='nomal', max_length=80),
        ),
    ]
