# Generated by Django 2.0.13 on 2019-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'United States of America'), ('sg', 'Singapore'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('cn', 'China'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('kr', 'Korea')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('female', 'Female'), ('not_specified', 'Not specified'), ('foregin_female', 'Foregin_Female')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('us', 'United States of America'), ('sg', 'Singapore'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('cn', 'China'), ('id', 'Indonesia'), ('vn', 'Viet Nam'), ('kr', 'Korea')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('company', 'Company'), ('common', 'Common')], default='nomal', max_length=80),
        ),
    ]
