# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190424_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('sg', 'Singapore'), ('id', 'Indonesia'), ('cn', 'China'), ('us', 'United States of America'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('kr', 'Korea'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('female', 'Female'), ('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('sg', 'Singapore'), ('id', 'Indonesia'), ('cn', 'China'), ('us', 'United States of America'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('kr', 'Korea'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('company', 'Company'), ('artist', 'Artist')], default='nomal', max_length=80),
        ),
    ]
