# Generated by Django 2.0.13 on 2019-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('id', 'Indonesia'), ('cn', 'China'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('sg', 'Singapore'), ('kr', 'Korea')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('male', 'Male'), ('foregin_male', 'Foregin_Male'), ('female', 'Female')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('id', 'Indonesia'), ('cn', 'China'), ('jp', 'Japan'), ('hk', 'Hong Kong'), ('vn', 'Viet Nam'), ('us', 'United States of America'), ('sg', 'Singapore'), ('kr', 'Korea')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('artist', 'Artist'), ('common', 'Common'), ('company', 'Company')], default='nomal', max_length=80),
        ),
    ]
