# Generated by Django 2.0.13 on 2019-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('id', 'Indonesia'), ('cn', 'China'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('us', 'United States of America'), ('kr', 'Korea'), ('sg', 'Singapore'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_male', 'Foregin_Male'), ('male', 'Male'), ('foregin_female', 'Foregin_Female'), ('female', 'Female'), ('not_specified', 'Not specified')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('id', 'Indonesia'), ('cn', 'China'), ('hk', 'Hong Kong'), ('jp', 'Japan'), ('us', 'United States of America'), ('kr', 'Korea'), ('sg', 'Singapore'), ('vn', 'Viet Nam')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('artist', 'Artist'), ('company', 'Company')], default='nomal', max_length=80),
        ),
    ]
