# Generated by Django 2.0.13 on 2019-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'United States of America'), ('cn', 'China'), ('hk', 'Hong Kong'), ('kr', 'Korea'), ('sg', 'Singapore'), ('vn', 'Viet Nam'), ('id', 'Indonesia'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('not_specified', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('foregin_male', 'Foregin_Male')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('us', 'United States of America'), ('cn', 'China'), ('hk', 'Hong Kong'), ('kr', 'Korea'), ('sg', 'Singapore'), ('vn', 'Viet Nam'), ('id', 'Indonesia'), ('jp', 'Japan')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('artist', 'Artist'), ('common', 'Common')], default='nomal', max_length=80),
        ),
    ]
