# Generated by Django 2.0.13 on 2019-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('vn', 'Viet Nam'), ('jp', 'Japan'), ('us', 'United States of America'), ('id', 'Indonesia'), ('kr', 'Korea'), ('hk', 'Hong Kong'), ('cn', 'China'), ('sg', 'Singapore')], default='kr', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('foregin_female', 'Foregin_Female'), ('female', 'Female'), ('male', 'Male'), ('not_specified', 'Not specified'), ('foregin_male', 'Foregin_Male')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_country',
            field=models.CharField(blank=True, choices=[('vn', 'Viet Nam'), ('jp', 'Japan'), ('us', 'United States of America'), ('id', 'Indonesia'), ('kr', 'Korea'), ('hk', 'Hong Kong'), ('cn', 'China'), ('sg', 'Singapore')], default='kr', max_length=80),
        ),
    ]
